# **INTRODUCTION TO PYTHON**
## **BASIC PYTHON SYNTAX**

### **This is my first interaction with Python (Basic Python Syntax and Codes)**

In [4]:
print("Hello, world")
print

Hello, world

# **Python Data types with Syntax examples**
# **1. Integer**

In [5]:
x=20  
x

20

## **2.Float**

In [6]:
y=3.14  #Float
print (y)

3.14

## **3. String**

In [7]:
name="Brender"   # string
print (name)

Brender

In [8]:
greeting= 'Hello'
greeting

'Hello'

## **4.Boolean:Represent True or False values**

In [9]:
is_valid=True 
is_valid

True

In [10]:
is_active=False
is_active

False

## **5.List:An ordered,mutable collection of items**

In [11]:
fruits=["apples","banana","orange"]
fruits

['apples', 'banana', 'orange']

In [12]:
fruits=["apples","banana","orange"]
print(fruits[0]) # Access first element
print(fruits[1]) #Access second element
print(fruits [2]) # Access third element

apples
banana
orange

## **6.Tuple:An ordered,immutable collection of items**

In [13]:
my_tuple=(1,2,3,"Brender",True)
my_tuple

(1, 2, 3, 'Brender', True)

In [14]:
coordinates=(10,20)
print(coordinates[1]) #Access the second element

20

## **7.Set**

In [15]:
my_set={1,2,3,"Brender"}
my_set

{1, 2, 3, 'Brender'}

## **8.Dictionary**

In [16]:
my_dict={"name":"Brender",
        "Age":22,
        "gender":"Female",
        "Occupation":"Statician"}
my_dict

{'name': 'Brender', 'Age': 22, 'gender': 'Female', 'Occupation': 'Statician'}

In [17]:
person={"name":"Brender",
       "Age":"22",
       "gender":"Female"}
person

{'name': 'Brender', 'Age': '22', 'gender': 'Female'}

In [18]:
print(person["name"])  #Access value by key

Brender

In [19]:
print(my_dict["Occupation"])

Statician

## **10.What are Conditional Statements?**

## **a.If Statement(do something if true)**

In [20]:
age=18

if age>=18:
    print("You are an adult")

You are an adult

## **b.If-else statement**

In [21]:
age=15

if age>=18:
    print("You are an adult")
else:
    print("You are a minor")

You are a minor

## **c.If-elif-else Statement(multiple conditions)**

In [22]:
age=18
if age>=18:
    print("Adult")
else:
    print("Minor")

Adult

In [23]:
age=12
if age>=18:
    print("Adult")
else:
    print("Minor")

Minor

In [24]:
age=45
if age>=18:
    print("Adult")
else:
    print("Minor")

Adult

In [25]:
score= 85

if score>=90:
    print("Grade:A")
elif score >=80:
    print("Grade:B")  
elif score>=70:
    print("Grade:C")
else:
    print("Grade:F")

Grade:B

In [26]:
score= 98

if score>=90:
    print("Grade:A")
elif score >=80:
    print("Grade:B")  
elif score>=70:
    print("Grade:C")
else:
    print("Grade:F")

Grade:A

In [27]:
score= 56

if score>=90:
    print("Grade:A")
elif score >=80:
    print("Grade:B")  
elif score>=70:
    print("Grade:C")
else:
    print("Grade:F")

Grade:F

In [28]:
score= 74

if score>=90:
    print("Grade:A")
elif score >=80:
    print("Grade:B")  
elif score>=70:
    print("Grade:C")
else:
    print("Grade:F")

Grade:C

## **11. What are loops?**
### **Basic Loops**

In [29]:
# For loop
for i in range(5):
    print(i)

0
1
2
3
4

In [30]:
# For loop
for i in range(3):
    print(i)

0
1
2

In [31]:
# For loop
for i in range(8):
    print(i)

0
1
2
3
4
5
6
7

## **Loop through a List**

In [32]:
fruits=['apple', 'banana','cherry']

for fruits in fruits:
    print(fruits)

apple
banana
cherry

## **Loop through a string**

In [33]:
word="python"

for letter in word:
    print(letter)

p
y
t
h
o
n

In [34]:
word="Brender"

for letter in word:
    print(letter)

B
r
e
n
d
e
r

## **Data Science Example-Loop through DataFrame**

In [35]:
import pandas as pd

#Create sample data
data = {
    'name':['Alice','Nyakio','Mwende'],
    'Score':[85,62,90]
}

df = pd.DataFrame(data)

#Loop through rows
for index, row in df.iterrows():
    print(f"{row['name']} scored {row['Score']}")

Alice scored 85
Nyakio scored 62
Mwende scored 90

In [36]:
import pandas as pd

#Create sample data
data = {
    'name':['Alice','Nyakio','Mwende'],
    'Score':[85,62,90]
}

df = pd.DataFrame(data)
df

     name  Score
0   Alice     85
1  Nyakio     62
2  Mwende     90

## **12.Functions**

In [37]:
def greet(name):
    return "Hello," + name

print(greet("Muriithi"))

Hello,Muriithi

## **13.Install Necessary Libraries**

In [38]:
#!pip install pandas
#!pip install numpy
#!pip install seaborn
#!pip install matplotlib
#!pip install wordcloud
#!pip install pillow
#!pip install plotly.express

## **14.Importing Libraries**

In [39]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# **Math Operations**

## **1.Basic Arithmetic Operations**

In [40]:
x = 10
y = 3

addition = x+y
subtraction = x-y
multiplication = x*y
division = x/y
floor_division = x//y
modulus = x % y
exponentiation = x**y

print (addition, subtraction, multiplication, division, floor_division, modulus, exponentiation)

13 7 30 3.3333333333333335 3 1 1000

In [41]:
print(addition)

13

In [42]:
print(subtraction)

7

## **3.Round function**

In [43]:
import math
num = 5.6789
rounded_value = round(num, 3)
floor_value = math.floor(num)
ceil_value = math.ceil(num)

print(rounded_value, floor_value, ceil_value)

5.679 5 6

## **Working with vectors in pyton**

In [44]:
import numpy as np

vector_a = np.array([1, 2, 3])
vector_a

array([1, 2, 3])

In [45]:
vector_b = np.array([4, 5, 6])
vector_b

array([4, 5, 6])

## **Vector addition**

In [46]:
vector_sum = vector_a + vector_b
vector_sum

array([5, 7, 9])

## **vector substraction**

In [47]:
vector_diff = vector_a - vector_b
vector_diff

array([-3, -3, -3])

## **scalar multiplication**

In [48]:
scalar_multiplication = 3*vector_a
scalar_multiplication

array([3, 6, 9])

In [49]:
scalar_multiplication = 3*vector_b
scalar_multiplication

array([12, 15, 18])

## **Dot product**

In [50]:
dot_product = np.dot(vector_a, vector_b)
dot_product
print("dot product:", dot_product)

dot product: 32

## **Magnitude of a vector**

In [51]:
magnitude_a = np.linalg.norm(vector_a)
magnitude_a
print("magnitude of a:", magnitude_a)
rounded_value = round(magnitude_a, 3)
print("magnitude of a:", rounded_value)
rounded_value = round(magnitude_a, 2)
print("magnitude of a:", rounded_value)

rounded_value = round(magnitude_a, 1)
print("magnitude of a:", rounded_value)

magnitude of a: 3.7416573867739413
magnitude of a: 3.742
magnitude of a: 3.74
magnitude of a: 3.7

In [52]:
print("Vector A:", vector_a)
print("Vector B:", vector_b)
print("Vector Sum:", vector_sum)
print("Vector Difference:", vector_diff)

Vector A: [1 2 3]
Vector B: [4 5 6]
Vector Sum: [5 7 9]
Vector Difference: [-3 -3 -3]

## **Working with list in python**
### **Creating a list**

In [53]:
fruits = ["Apple", "Banana", "Cherry", "Date"]
fruits

['Apple', 'Banana', 'Cherry', 'Date']

### **Accessing elements**

In [54]:
first_fruit = fruits[0]
first_fruit

'Apple'

In [55]:
last_fruit = fruits[-1]
last_fruit

'Date'

In [56]:
last_fruit = fruits[-2]
last_fruit

'Cherry'

In [57]:
fruits[1] = "Blueberry" # change Banana to Blueberry- modifying elements
fruits

['Apple', 'Blueberry', 'Cherry', 'Date']

In [58]:
fruits[-3] = "Blueberry" # change Banana to Blueberry- modifying elements
fruits

['Apple', 'Blueberry', 'Cherry', 'Date']

### **Adding elements**

In [59]:
fruits.append("Elderberry") # Append new element to the end - Adding elements
fruits.insert(2, "coconut") # Insert at index 2

In [60]:
deleted_fruit = fruits.pop(3) # Remove and return element at index 3 - Remove
fruits.remove("Date")  # Remove first occurence of "Apple"
fruits

['Apple', 'Blueberry', 'coconut', 'Elderberry']

### **List Slicing**

In [61]:
subset_fruits = fruits[1:3] # Get elements from index 1 to 2
subset_fruits

['Blueberry', 'coconut']

### **Iterating over a list**

In [62]:
for fruit in fruits:
    print(fruit)

Apple
Blueberry
coconut
Elderberry

### **finding the length of a list**

In [63]:
num_fruits = len(fruits)
num_fruits

4

In [64]:
print("Updated Fruits List:", fruits)

Updated Fruits List: ['Apple', 'Blueberry', 'coconut', 'Elderberry']

In [65]:
print("Deleted Fruit:", deleted_fruit)

Deleted Fruit: Cherry

In [66]:
print("Subset of Fruits:", subset_fruits)

Subset of Fruits: ['Blueberry', 'coconut']

In [67]:
print("Number of Fruits:", num_fruits)

Number of Fruits: 4

# **Matrices**

### **Defn- a Matrix is a 2D array of numbers arranged in rows and column**

#### **Quick Practice Exercise**

In [68]:
import numpy as np

# Create two 2x2 matrices
A = np.array([[1,2],
              [3,4]])
B = np.array([[2,0],
              [1,2]])

In [69]:
# Perform operations
print("A + B =\n", A + B)

A + B =
 [[3 2]
 [4 6]]

In [70]:
print("\nA - B =\n", A - B)

A - B =
 [[-1  2]
 [ 2  2]]

In [71]:
print("\nA X B (element-wise) =\n", A * B)

A X B (element-wise) =
 [[2 0]
 [3 8]]

In [72]:
print("\nA@ B (matrix multiplication) =\n", A @ B)

A@ B (matrix multiplication) =
 [[ 4  4]
 [10  8]]

In [73]:
print("\nTranspose of A =\n", A.T)

Transpose of A =
 [[1 3]
 [2 4]]

## **Create DataFrame Using Pandas(Most Common)**

In [77]:
import pandas as pd

# Create a DataFrame
data = {
    "Name":["Alice", "Nyakio", "Mwende", "Christine", "Matthew"],
    "Age":[25, 30, 35, 40, 80],
    "County":["Muranga", "Meru","Embu", "Nyeri", "Kirinyaga"]
}

df = pd.DataFrame(data)
df

        Name  Age     County
0      Alice   25    Muranga
1     Nyakio   30       Meru
2     Mwende   35       Embu
3  Christine   40      Nyeri
4    Matthew   80  Kirinyaga

In [78]:
import 

print(df.tail())

SyntaxError: Expected one or more names after 'import' (3361677126.py, line 1)

In [79]:
df["County"]

0      Muranga
1         Meru
2         Embu
3        Nyeri
4    Kirinyaga
Name: County, dtype: object

In [80]:
df["Age"]

0    25
1    30
2    35
3    40
4    80
Name: Age, dtype: int64

In [81]:
df["Name"]

0        Alice
1       Nyakio
2       Mwende
3    Christine
4      Matthew
Name: Name, dtype: object

### **Accessing Rows**

In [82]:
print("\nAccessing first row:")
print(df.iloc[0])

Accessing first row:
Name        Alice
Age            25
County    Muranga
Name: 0, dtype: object

### **Adding a New Column**

In [83]:
df["Salary"] = [50000, 60000,70000,80000,90000]
df['occupation'] = ['Nurse', 'Teacher', 'Politician', 'Doctor', 'Nurse']
df

        Name  Age     County  Salary  occupation
0      Alice   25    Muranga   50000       Nurse
1     Nyakio   30       Meru   60000     Teacher
2     Mwende   35       Embu   70000  Politician
3  Christine   40      Nyeri   80000      Doctor
4    Matthew   80  Kirinyaga   90000       Nurse

### **Filtering**

In [84]:
df[df["Age"] > 30]

        Name  Age     County  Salary  occupation
2     Mwende   35       Embu   70000  Politician
3  Christine   40      Nyeri   80000      Doctor
4    Matthew   80  Kirinyaga   90000       Nurse

In [85]:
df[df["Age"] > 34]

        Name  Age     County  Salary  occupation
2     Mwende   35       Embu   70000  Politician
3  Christine   40      Nyeri   80000      Doctor
4    Matthew   80  Kirinyaga   90000       Nurse

### **Sorting Data**

In [86]:
df.sort_values(by="Age", ascending=False)

        Name  Age     County  Salary  occupation
4    Matthew   80  Kirinyaga   90000       Nurse
3  Christine   40      Nyeri   80000      Doctor
2     Mwende   35       Embu   70000  Politician
1     Nyakio   30       Meru   60000     Teacher
0      Alice   25    Muranga   50000       Nurse

In [87]:
df.sort_values(by="Age", ascending=True)

        Name  Age     County  Salary  occupation
0      Alice   25    Muranga   50000       Nurse
1     Nyakio   30       Meru   60000     Teacher
2     Mwende   35       Embu   70000  Politician
3  Christine   40      Nyeri   80000      Doctor
4    Matthew   80  Kirinyaga   90000       Nurse

### **Grouping Data**

In [88]:
df.groupby("County")["Age"].mean()

County
Embu         35.0
Kirinyaga    80.0
Meru         30.0
Muranga      25.0
Nyeri        40.0
Name: Age, dtype: float64

### **Handling Missing Data**
#### **Introduce a missing value**

In [89]:
df.loc[2,"Salary"] = None #continous
df

        Name  Age     County   Salary  occupation
0      Alice   25    Muranga  50000.0       Nurse
1     Nyakio   30       Meru  60000.0     Teacher
2     Mwende   35       Embu      NaN  Politician
3  Christine   40      Nyeri  80000.0      Doctor
4    Matthew   80  Kirinyaga  90000.0       Nurse

## **Suppress Warnings**

In [91]:
import warnings

warnings.simplefilter("ignore")

In [92]:
df["Salary"].fillna(df["Salary"].mean(), inplace=True)
df

        Name  Age     County   Salary  occupation
0      Alice   25    Muranga  50000.0       Nurse
1     Nyakio   30       Meru  60000.0     Teacher
2     Mwende   35       Embu  70000.0  Politician
3  Christine   40      Nyeri  80000.0      Doctor
4    Matthew   80  Kirinyaga  90000.0       Nurse

In [93]:
df.loc[2,"occupation"] = None #categorical
df

        Name  Age     County   Salary occupation
0      Alice   25    Muranga  50000.0      Nurse
1     Nyakio   30       Meru  60000.0    Teacher
2     Mwende   35       Embu  70000.0       None
3  Christine   40      Nyeri  80000.0     Doctor
4    Matthew   80  Kirinyaga  90000.0      Nurse

In [95]:
df["occupation"].fillna(df["occupation"].mode()[0], inplace=True)
df

        Name  Age     County   Salary occupation
0      Alice   25    Muranga  50000.0      Nurse
1     Nyakio   30       Meru  60000.0    Teacher
2     Mwende   35       Embu  70000.0      Nurse
3  Christine   40      Nyeri  80000.0     Doctor
4    Matthew   80  Kirinyaga  90000.0      Nurse

# **Exercise:Create dataframe**

In [102]:
data ={'Name':['Kevo','Brayo','Brender','Phylis','Evans','Jayke','Doreen','Caro','Jane','Mercy'],
      'Age':[20,21,24,23,26,19,25,22,28,29],
       'Salary':[4000,5000,8000,3000,2000,750,800,1250,600,1350],
       'County':['Chuka','Embu','Nairobi','Rongai','Thika','Kenol','Kerugoya','Nakuru','Muranga','Kisii'],
      'Institution':['Chuka','UoE','Cooperative','Multimedia','UON','JKUAT','Kirinyaga ','Egerton','TUK','Kisii ']
}
df = pd.DataFrame(data)
print(df)

      Name  Age  Salary    County  Institution
0     Kevo   20    4000     Chuka        Chuka
1    Brayo   21    5000      Embu          UoE
2  Brender   24    8000   Nairobi  Cooperative
3   Phylis   23    3000    Rongai   Multimedia
4    Evans   26    2000     Thika          UON
5    Jayke   19     750     Kenol        JKUAT
6   Doreen   25     800  Kerugoya   Kirinyaga
7     Caro   22    1250    Nakuru      Egerton
8     Jane   28     600   Muranga          TUK
9    Mercy   29    1350     Kisii       Kisii

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         10 non-null     object
 1   Age          10 non-null     int64
 2   Salary       10 non-null     int64
 3   County       10 non-null     object
 4   Institution  10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes